### PR TITLE
Strip area markers early

### PR DESCRIPTION
**Pull request by original-birdman**
As requested...

### CODE REVIEW

**Comment by original-birdman** [comment]
The idea would then be to later remove various other bits of code that do this once we/I can figure out that they are no longer needed, as this has already done it.

**Comment by AbuBaniaz** [comment]
@original-birdman 
Something is not quite right with this pull request

**Comment by original-birdman** [comment]
Hmmmm....I see what you mean.
No idea what caused that.

**Comment by original-birdman** [comment]
I _suspect_ the problem is that this is comparing my (new/edited) branch, which is based on today's Dev, against your Dev, which is 2 days old.

I can't fork "your" Dev and edit that, as all it does is move to the fork I've already got of enigma2.

**Comment by original-birdman** [comment]
I've deleted my fork, created a new one, cloned it, switched to Dev, created `StripAreaMarkers` as a new branch from that, updated the file and committed the change.
I've then pushed the new branch back (`git push -u origin StripAreaMarkers`).

Trying to create a PR against your fork _still_ shows 4 files changed.

The only oddity I see is that while `Dev` and `master` in my fork are even with the OpenViX branches, `StripAreaMarkers` claims to be 1 commit ahead and 509 behind.

**Comment by Huevos** [comment]
Yes because the fork is not my repo.

**Comment by Huevos** [comment]
Gordon, where is the commit?

**Comment by original-birdman** [comment]
I deleted my fork to start again, so the commit went away.
I can generate another (it's only a one-line change, plus adding a comment).

**Comment by original-birdman** [comment]
> Yes because the fork is not my repo.

I can't fork a fork...

**Comment by original-birdman** [comment]
This is a (closed) PR against OpenViX::Dev (which works)

https://github.com/OpenViX/enigma2/pull/478

**Comment by original-birdman** [comment]
Here's one that looks correct:

https://github.com/Huevos/enigma2/pull/68

**Pull request closed without merging**
